# Generated by Django 4.2.4 on 2023-08-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotareas',
            name='observaciones_tarea',
            field=models.TextField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrotareas',
            name='descripcion_tarea',
            field=models.CharField(max_length=80, verbose_name='Descripción de tarea'),
        ),
    ]
